version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "Fase de instalação do interpretador Js"
    pre_build:
        commands: 
            - echo "Fase de Pre Build realizado em" `date`
    build:
        commands:
            - echo "Fase de build" 
            - echo "Fase de testes"
            - grep -Fq "Congratulations" index.html
    post_build:
        commands:
            - echo "Fase final do build"
            
artifacts:  
  files:
    - '**/**'
  name: my-webapp-artifacts